BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Truck] (
    [id] NVARCHAR(1000) NOT NULL,
    [truckCode] NVARCHAR(1000) NOT NULL,
    [status] NVARCHAR(1000) NOT NULL,
    [x] FLOAT(53) NOT NULL,
    [y] FLOAT(53) NOT NULL,
    [isLoaded] BIT NOT NULL CONSTRAINT [Truck_isLoaded_df] DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Truck_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Truck_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [Truck_truckCode_key] UNIQUE NONCLUSTERED ([truckCode])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
