<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\TrackingDemo.Application\TrackingDemo.Application.csproj" />
    <ProjectReference Include="..\TrackingDemo.Infrastructure\TrackingDemo.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <PropertyGroup>
    <RootNamespace>TrackingDemo.Api</RootNamespace>
  </PropertyGroup>
</Project>
